# Generated by Django 5.2.14 on 2026-05-08 23:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('difficulty', models.CharField(choices=[('A', 'A Rank'), ('S', 'S Rank'), ('SS', 'SS Rank')], default='A', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('coin_reward', models.PositiveIntegerField(default=25)),
                ('hp', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('reset_weekly', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('coin_reward', models.PositiveIntegerField(default=0)),
                ('attribute_rewards', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('work', 'Work'), ('german', 'German'), ('fitness', 'Fitness'), ('health', 'Health'), ('recovery', 'Recovery'), ('hygiene', 'Hygiene'), ('home', 'Home')], default='health', max_length=40)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_million', models.DecimalField(decimal_places=2, max_digits=8, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('xp_reward', models.PositiveIntegerField(default=75)),
                ('coin_reward', models.PositiveIntegerField(default=20)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['amount_million'],
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('coin_reward', models.PositiveIntegerField(default=2)),
                ('attribute_rewards', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('work', 'Work'), ('german', 'German'), ('fitness', 'Fitness'), ('health', 'Health'), ('shipping', 'Shipping'), ('social', 'Social')], default='work', max_length=40)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GiftFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount_million', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('target_amount_million', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_fund', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='Lost Starter', max_length=80)),
                ('hp', models.PositiveSmallIntegerField(default=82, validators=[django.core.validators.MaxValueValidator(100)])),
                ('stamina', models.PositiveSmallIntegerField(default=72, validators=[django.core.validators.MaxValueValidator(100)])),
                ('focus', models.PositiveSmallIntegerField(default=76, validators=[django.core.validators.MaxValueValidator(100)])),
                ('momentum', models.PositiveSmallIntegerField(default=64, validators=[django.core.validators.MaxValueValidator(100)])),
                ('intelligence', models.PositiveIntegerField(default=12)),
                ('discipline', models.PositiveIntegerField(default=10)),
                ('strength', models.PositiveIntegerField(default=8)),
                ('communication', models.PositiveIntegerField(default=7)),
                ('charisma', models.PositiveIntegerField(default=7)),
                ('builder', models.PositiveIntegerField(default=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuickActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.quickaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bonus_type', models.CharField(choices=[('combo', 'Combo Bonus'), ('perfect_day', 'Perfect Day')], max_length=30)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'bonus_type'), name='unique_daily_bonus_claim')],
            },
        ),
        migrations.CreateModel(
            name='BossProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.PositiveIntegerField(default=0)),
                ('cleared', models.BooleanField(default=False)),
                ('week_start', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.boss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['boss__ordering'],
                'constraints': [models.UniqueConstraint(fields=('user', 'boss', 'week_start'), name='unique_weekly_boss_progress')],
            },
        ),
        migrations.CreateModel(
            name='GiftMilestoneUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='core.giftmilestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_milestone_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'milestone'), name='unique_gift_milestone_unlock')],
            },
        ),
        migrations.CreateModel(
            name='MentalCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('energy', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('focus', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('motivation', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('control', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_mental_checkin')],
            },
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.dailyquest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'quest', 'date'), name='unique_daily_quest_completion')],
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_reflection')],
            },
        ),
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=60)),
                ('source_key', models.CharField(blank=True, max_length=180)),
                ('xp_delta', models.IntegerField(default=0)),
                ('coin_delta', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('week_start', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'week_start'], name='core_reward_user_id_6f485b_idx'), models.Index(fields=['source', 'source_key'], name='core_reward_source_a26dbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmokingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cigarettes_count', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoking_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_smoking_log')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('xp_gained', models.IntegerField(default=0)),
                ('quests_completed', models.PositiveIntegerField(default=0)),
                ('perfect_days', models.PositiveIntegerField(default=0)),
                ('german_sessions', models.PositiveIntegerField(default=0)),
                ('gym_sessions', models.PositiveIntegerField(default=0)),
                ('issues_closed', models.PositiveIntegerField(default=0)),
                ('smoking_limit_days', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='unique_weekly_archive')],
            },
        ),
    ]
