# Generated by Django 5.2.14 on 2026-05-09 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomEventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(default='state', max_length=60)),
                ('effect_description', models.TextField(blank=True)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], default='Common', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['ordering', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('consumable', 'Consumable'), ('food', 'Food'), ('recovery', 'Recovery'), ('style', 'Style'), ('gear', 'Gear'), ('experience', 'Experience')], default='consumable', max_length=40)),
                ('required_level', models.PositiveSmallIntegerField(default=1)),
                ('allow_repeat', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['ordering', 'cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyBossTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('difficulty', models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], default='Rare', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('xp_reward', models.PositiveIntegerField(default=120)),
                ('coin_reward', models.PositiveIntegerField(default=30)),
                ('attribute_rewards', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(default='growth', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='growth', max_length=60)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('coin_reward', models.PositiveIntegerField(default=12)),
                ('attribute_rewards', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['ordering', 'title'],
            },
        ),
        migrations.AddField(
            model_name='giftmilestone',
            name='badge_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='giftmilestone',
            name='title_reward',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='WeeklyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('chapter_name', models.CharField(max_length=120)),
                ('generated_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRandomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_events', to='core.randomeventtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_random_events', to=settings.AUTH_USER_MODEL)),
                ('weekly_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='random_event', to='core.weeklyrun')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyChallengeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_challenge_instances', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.weeklychallengetemplate')),
                ('weekly_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_instances', to='core.weeklyrun')),
            ],
            options={
                'ordering': ['template__ordering', 'template__title'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyBossInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.PositiveIntegerField()),
                ('max_hp', models.PositiveIntegerField()),
                ('cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_boss_instances', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.weeklybosstemplate')),
                ('weekly_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss_instance', to='core.weeklyrun')),
            ],
            options={
                'ordering': ['-weekly_run__week_start'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_gained', models.IntegerField(default=0)),
                ('coins_gained', models.IntegerField(default=0)),
                ('daily_quests_completed', models.PositiveIntegerField(default=0)),
                ('perfect_days', models.PositiveIntegerField(default=0)),
                ('quick_actions_completed', models.PositiveIntegerField(default=0)),
                ('german_sessions', models.PositiveIntegerField(default=0)),
                ('gym_sessions', models.PositiveIntegerField(default=0)),
                ('issues_closed', models.PositiveIntegerField(default=0)),
                ('smoking_limit_days', models.PositiveIntegerField(default=0)),
                ('bosses_cleared', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to=settings.AUTH_USER_MODEL)),
                ('weekly_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.weeklyrun')),
            ],
            options={
                'ordering': ['-weekly_run__week_start'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.shopitem')),
            ],
            options={
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['user', 'item'], name='core_purcha_user_id_59cbc5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyrun',
            index=models.Index(fields=['user', 'is_active'], name='core_weekly_user_id_574633_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyrun',
            constraint=models.UniqueConstraint(fields=('user', 'week_start'), name='unique_weekly_run_per_user_week'),
        ),
        migrations.AddConstraint(
            model_name='weeklychallengeinstance',
            constraint=models.UniqueConstraint(fields=('weekly_run', 'template'), name='unique_weekly_challenge_template_per_run'),
        ),
    ]
